version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timemanager_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

  backend:
    build:
      context: ./timemanager
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/timemanager_dev
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./timemanager:/app

  frontend:
    build:
      context: ./TimeManager_front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./TimeManager_front:/app

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
