version: '3'
services:
  postgres:
    container_name: timemanager_dev
    image: postgres
    environment:
      POSTGRES_DB: timemanager_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: