pipeline {
    agent {
        docker {
            image 'elixir:1.16.1-alpine' // Utilise une image Docker avec Elixir pré-installé
            args '-u root' // Exécute en tant que root pour permettre les installations
            reuseNode true
        }
    }

    environment {
        // DOCKER_REGISTRY = "your-docker-registry-url" // URL de ton registre Docker (ex: Docker Hub)
        DOCKER_IMAGE = "time-manager-backend"
        // DOCKER_CREDENTIALS_ID = "docker-credentials" // Identifiants Docker dans Jenkins
        COMPOSE_FILE = "docker-compose.yml"
    }
    
    stages {
        stage('Start Services') {
            steps {
                // Lancer les services avec docker-compose
                sh 'docker-compose -f $COMPOSE_FILE up -d db'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('timemanager') {
                    // Installe les dépendances
                    sh 'mix local.hex --force'
                    sh 'mix local.rebar --force'
                    sh 'mix deps.get'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('timemanager') {
                    // Compile le projet
                    sh 'mix compile'
                }
            }
            post {
                success {
                    echo 'Compile project successfully.'
                }
                failure {
                    echo 'Failed to compile project.'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('timemanager') {
                    // Exécute les tests
                    sh 'mix test'
                }
            }
            post {
                success {
                    echo 'All unit tests passed successfully.'
                }
                failure {
                    echo 'Unit tests failed. Please check the test logs for details.'
                }
            }
        }

        stage('Stop Services') {
            steps {
                // Arrête les services après les tests
                sh 'docker-compose -f $COMPOSE_FILE down'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build de l'image Docker pour le back
                script {
                    docker.build("${DOCKER_IMAGE}:latest")
                }
            }
            post {
                success {
                    echo 'Docker image built successfully.'
                }
                failure {
                    echo 'Docker image build failed. Please check the build configuration and logs.'
                }
            }
        }

        stage('Deploy local') {
            steps {
                sh '''
                docker run -d --name backend_container -p 4000:4000 time-manager-backend:latest
                '''
            }
        }

        // stage('Push Docker Image') {
        //     steps {
        //         // script {
        //         //     // Authentification et push de l'image vers le registre Docker
        //         //     // docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
        //         //     //     docker.image("${DOCKER_IMAGE}:latest").push()
        //         //     }
        //         // }
        //         echo 'Deploying the API...'
        //     }
        //     post {
        //         success {
        //             echo 'Deployment successful!'
        //         }
        //         failure {
        //             echo 'Deployment failed. Please check the deployment configuration and logs.'
        //         }
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         // Déploiement du backend
        //         sh '''
        //         docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
        //         docker stop my_backend_container || true
        //         docker rm my_backend_container || true
        //         docker run -d --name my_backend_container -p 4000:4000 ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
        //         '''
        //     }
        // }
    }

    // post {
    //     always {
    //         echo 'Pipeline completed.'
    //     }
    // }
}
