name: CI Front

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'

    - name: Install Dependencies
      working-directory: ./TimeManager_front
      run: npm install

    - name: Run Unit Tests
      working-directory: ./TimeManager_front
      run: npm run test:unit

    - name: Build Frontend
      working-directory: ./TimeManager_front
      run: npm run build

    - name: Deploy
      run: echo "Deploying the frontend..."
      # Ajoute ici les commandes de déploiement nécessaires.
      # Par exemple: scp -r ./TimeManager_front/dist/* user@server:/path/to/deploy
